#!/bin/sh

# Author:  Boris Pek <tehnick-8@mail.ru>
# License: Public Domain
# Created: 2012-11-29
# Updated: 2013-05-09
# Version: N/A
# Description: script for Debian Sid
# libc6 >= 2.17-1 is now available here, so extra libraries are not required

set -e

export STEAM_VER_LIST="$(curl 'http://repo.steampowered.com/steam/pool/steam/s/steam/' 2>&1 | sed -ne 's:^.*steam-launcher_\(.*\)_all.deb.*$:\1:p')"
if [ -z "${STEAM_VER}" ]; then
    export STEAM_VER=$(echo "${STEAM_VER_LIST}" | sort -r -V | head -n1)
fi
echo "STEAM_VER = ${STEAM_VER}"

mkdir -p tmp
cd tmp

if [ ! -e "steam-launcher_${STEAM_VER}_all.deb" ]; then
    wget -4 -c "http://repo.steampowered.com/steam/pool/steam/s/steam/steam-launcher_${STEAM_VER}_all.deb"
fi

rm -rf steam-launcher_deb
dpkg -x steam-launcher_${STEAM_VER}_all.deb steam-launcher_deb
dpkg -e steam-launcher_${STEAM_VER}_all.deb steam-launcher_deb/DEBIAN

rm steam-launcher_deb/DEBIAN/conffiles
#rm steam-launcher_deb/DEBIAN/md5sums
rm steam-launcher_deb/usr/bin/steamdeps
rm -r steam-launcher_deb/etc

sed -e "s|jockey-common, ||" -i steam-launcher_deb/DEBIAN/control

cd ..

dpkg -b tmp/steam-launcher_deb repackaged-steam_${STEAM_VER}_all.deb

echo "Package is ready for installation:"
echo "sudo dpkg -i repackaged-steam_${STEAM_VER}_all.deb"

